// Offline logic and event-integration checks: node tests/verify.cjs
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).filter(s=>s.trim());
scripts.forEach(s=>new vm.Script(s));const scope=vm.createContext({});vm.runInContext(scripts[0]+';globalThis.Engine=FlightMarket;globalThis.Wallet=Portfolio;',scope);const Engine=scope.Engine,Wallet=scope.Wallet;
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('Offline HTML, scripts, element IDs and UI references',()=>{assert.equal(scripts.length,2);assert.ok(!/<(?:script|link|img)[^>]*(?:src|href)=["']https?:/i.test(html));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const m of scripts[1].matchAll(/\$\('([^']+)'\)/g))assert.ok(ids.includes(m[1]),m[1]);});
test('Gravity, impulse, upper/lower boundaries and collision failure',()=>{const g=new Engine(()=>.5);g.start();g.update(.1);assert.ok(g.y<320&&g.vy>-335);g.flap();assert.equal(g.vy,-335);for(let i=0;i<40;i++)g.update(.1);assert.equal(g.state,'ended');assert.equal(g.outcome,'failed');g.start();g.y=17;g.flap();g.update(.02);assert.equal(g.outcome,'failed');});
test('Gap traversal, pipe body and protruding cap collisions',()=>{const g=new Engine(()=>.5);const pipe=()=>({x:g.birdX-30,width:66,center:320,gap:226,passed:false});g.start();g.vy=0;g.pipes=[pipe()];g.update(1/120);assert.equal(g.state,'running');g.y=195;g.update(1/120);assert.equal(g.outcome,'failed');g.start();g.y=450;g.vy=0;g.pipes=[pipe()];g.update(1/120);assert.equal(g.outcome,'failed');});
test('Score only after clearing the full pipe including cap',()=>{const g=new Engine(()=>.5);g.start();g.vy=0;g.pipes=[{x:g.birdX-g.radius-72,width:66,center:320,gap:226,passed:false}];g.update(1/120);assert.equal(g.score,1);g.update(.1);assert.equal(g.score,1);});
test('Paused and ended sessions freeze; trades rejected',()=>{const g=new Engine();g.start();g.update(.1);g.pause();let snapshot=JSON.stringify(g);g.update(2);g.flap();g.trade('buy',10);assert.equal(JSON.stringify(g),snapshot);g.resume();assert.equal(g.vy,-335);g.end('collision');snapshot=JSON.stringify(g);g.end('again');g.exit();g.trade('sell',100);g.update(1);assert.equal(JSON.stringify(g),snapshot);});
test('Wider 0.16-second OHLC, extrema, widths and immutable history',()=>{const g=new Engine(()=>.5);g.start();const values=[g.open];for(let i=0;i<20;i++){g.update(1/120);values.push(g.price);}assert.equal(g.history.length,1);const k=g.history[0];near(k.open,128);near(k.close,g.price);near(k.high,Math.max(...values));near(k.low,Math.min(...values));near(k.span,37.5);const frozen=JSON.stringify(k);g.update(.1);g.update(.1);assert.equal(JSON.stringify(k),frozen);assert.ok(g.history.length>=2);});
test('Physics identical at 30, 60, 144 Hz',()=>{const runs=[30,60,144].map(fps=>{const g=new Engine(()=>.5);g.start();for(let i=0;i<fps;i++){if(i===fps/2)g.flap();g.update(1/fps);}return g;});for(const g of runs.slice(1)){near(g.y,runs[0].y);near(g.price,runs[0].price);near(g.distance,runs[0].distance);assert.equal(g.history.length,runs[0].history.length);}});
test('World log-price coordinates retain sevenfold initial sensitivity and ignore camera motion',()=>{const g=new Engine();near(g.priceAt(320),128);for(const y of [100,300,340,800]){const price=g.priceAt(y);near(Math.log(price/128),7*(320-y)*.1/128);near(g.yAtPrice(price),y);}near(g.priceAt(10000),.01);const price=g.priceAt(340);g.cameraY=600;near(g.priceAt(340),price);});
test('Cost-basis arithmetic before fees',()=>{const p=new Wallet(0);assert.equal(p.cash,200000);assert.equal(p.buy(1000,100),100000);near(p.shares,10);p.buy(400,200);near(p.shares,12);assert.equal(p.cost,140000);assert.equal(p.equity(150),240000);assert.equal(p.sell(.5,150),90000);near(p.shares,6);assert.equal(p.cost,70000);assert.equal(p.realized,20000);p.sell(1,120);assert.equal(p.cash,222000);assert.equal(p.realized,22000);assert.equal(p.cost,0);assert.equal(p.shares,0);});
test('Trades use existing balances, enforce 20 percent cap, and never pause',()=>{const g=new Engine();g.start(600);near(g.portfolio.cash,140000);const y=g.y;assert.equal(g.trade('buy',10),14000);assert.equal(g.trade('buy',10),12600);let units=g.portfolio.shares;g.trade('sell',10);near(g.portfolio.shares,units*.9);const snapshot=JSON.stringify(g.portfolio);for(const rate of [20.01,21,50,100]){g.trade('buy',rate);g.trade('sell',rate);}assert.equal(JSON.stringify(g.portfolio),snapshot);const cash=g.portfolio.cash;assert.equal(g.trade('buy',20),Math.round(cash*.2));units=g.portfolio.shares;g.trade('sell',20);near(g.portfolio.shares,units*.8);assert.equal(g.state,'running');g.update(.05);assert.notEqual(g.y,y);});
test('Invalid amounts and overdraw cannot alter account',()=>{const p=new Wallet();for(const amount of [NaN,Infinity,-1,2001,0])assert.equal(p.buy(amount,100),0);assert.equal(p.cash,200000);assert.equal(p.sell(2,100),0);const g=new Engine();assert.equal(g.start(2001),false);g.start(0);const snapshot=JSON.stringify(g.portfolio);for(const rate of [0,-10,21,101,NaN,Infinity])g.trade('buy',rate);assert.equal(JSON.stringify(g.portfolio),snapshot);});
test('Crash with a profit is still failure; zero assets is bankruptcy',()=>{const g=new Engine();g.start(2000);g.y=100;g.sample();assert.ok(g.portfolio.equity(g.price)>200000);g.end('crash');assert.equal(g.outcome,'failed');g.start();g.portfolio.cash=0;g.portfolio.shares=0;g.checkBankruptcy();assert.equal(g.state,'ended');assert.equal(g.outcome,'failed');assert.match(g.reason,/破产/);});
test('Voluntary exits classify profit, loss, flat; settlement once',()=>{for(const [y,outcome]of [[100,'won'],[500,'loss'],[320,'loss']]){const g=new Engine();g.start(1000);g.y=y;g.sample();g.score=8;g.exit();assert.equal(g.outcome,outcome);assert.equal(g.portfolio.shares,0);const before=JSON.stringify(g.portfolio);g.exit();assert.equal(JSON.stringify(g.portfolio),before);}});
test('Every new round starts at 2000 with no accumulated funds',()=>{const g=new Engine();g.start(2000);g.y=100;g.sample();g.exit();g.reset();assert.equal(g.portfolio.cash,200000);assert.equal(g.portfolio.shares,0);assert.equal(g.portfolio.realized,0);assert.equal(g.history.length,0);assert.equal(g.score,0);assert.equal(g.price,128);g.start(1000);assert.equal(g.portfolio.cash,100000);assert.equal(g.portfolio.equity(g.price),199000);});
test('Fees are charged on both sides, included in cost basis and settlement',()=>{const p=new Wallet();p.buy(1000,100);near(p.shares,9.9);assert.equal(p.cash,100000);assert.equal(p.cost,100000);assert.equal(p.fees,1000);assert.equal(p.saleQuote(1,100).proceeds,98010);p.sell(1,100);assert.equal(p.cash,198010);assert.equal(p.realized,-1990);assert.equal(p.fees,1990);assert.equal(p.shares,0);});
test('Exit lock blocks opening-price profit until eight pipes; then settles once',()=>{const g=new Engine();g.start(1000);g.y=100;g.sample();const before=JSON.stringify(g.portfolio);assert.equal(g.exit(),false);assert.equal(JSON.stringify(g.portfolio),before);g.score=7;assert.equal(g.exit(),false);g.score=8;assert.equal(g.exit(),true);assert.equal(g.outcome,'won');const settled=JSON.stringify(g.portfolio);assert.equal(g.exit(),false);assert.equal(JSON.stringify(g.portfolio),settled);g.start(0);g.score=8;g.exit();assert.equal(g.outcome,'flat');});
test('200 seeded runs: scrolling bearish routes and reachable 40-pipe paths',()=>{
  let biggestRise=0,biggestFall=0,losses=0;
  for(const width of [380,1000])for(let seed=1;seed<=100;seed++){
    let n=seed;const g=new Engine(()=>((n=(n*1664525+1013904223)>>>0)/4294967296));g.width=width;g.start();
    for(let step=0;step<45000&&g.score<40&&g.state==='running';step++){
      const next=g.pipes.find(p=>!p.passed);assert.ok(next);
      biggestRise=Math.max(biggestRise,-next.delta);biggestFall=Math.max(biggestFall,next.delta);
      assert.ok(g.y-g.cameraY>g.radius&&g.y-g.cameraY<640-g.radius);
      if(Engine.pilot(g.y,g.vy,next.center))g.flap();g.update(1/120);
    }
    assert.ok(g.score>=40,`width ${width}, seed ${seed}: score ${g.score}, ${g.reason}`);if(g.portfolio.equity(g.price)<200000)losses++;
  }
  assert.ok(biggestRise>=45&&biggestFall>23,`rise ${biggestRise}, fall ${biggestFall}`);assert.ok(losses>120,`only ${losses}/200 passive holders lost`);console.log(`  Passive holders lost in ${losses}/200 runs.`);
});
test('Rallies only at multiples of 30, strict 50 percent threshold and independent later checkpoints',()=>{
  const g=new Engine(()=>.75);g.start();while(g.generated<29)g.addPipe();g.random=()=>.499999;g.addPipe();const rally=g.pipes.at(-1);assert.equal(rally.index,30);assert.equal(rally.rally,true);assert.ok(rally.delta<=-45);g.random=()=>.5;while(g.generated<60)g.addPipe();assert.equal(g.pipes.at(-1).rally,false);g.random=()=>0;while(g.generated<90)g.addPipe();assert.equal(g.pipes.at(-1).rally,true);for(const p of g.pipes){if(p.rallyTrigger)assert.equal(p.index%30,0);if(!p.rally) assert.ok(p.delta>=-28&&p.delta<=35);}
});
test('Rally frequency stays near half over 750 seeded checkpoints',()=>{
  let count=0,opportunities=0;
  for(let seed=1;seed<=250;seed++){let n=seed;const g=new Engine(()=>((n=(n*1664525+1013904223)>>>0)/4294967296));g.start();while(g.generated<90)g.addPipe();for(const p of g.pipes){if(p.index%30===0){opportunities++;if(p.rally)count++;}else assert.equal(p.rallyTrigger,false);}}
  assert.equal(opportunities,750);assert.ok(count/opportunities>.42&&count/opportunities<.58);console.log('  Rally checkpoints: '+count+'/'+opportunities);
});
// DOM/canvas doubles test integration, not actual browser rendering.
test('UI: live hotkeys/buttons, custom percentage, input guards, outcomes, reload reset',()=>{
  const elements=new Map(),handlers={},windowHandlers={};let frame,clock=0;
  const context=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});
  function el(id){if(!elements.has(id))elements.set(id,{id,hidden:false,value:id==='initial'?'600':id==='rate'?'10':'',textContent:'',width:1000,height:640,offsetWidth:1000,events:{},classList:{add(){},remove(){}},setAttribute(){},focus(){},blur(){},getContext:()=>context,getBoundingClientRect:()=>({width:1000,height:640}),addEventListener(type,fn){this.events[type]=fn;}});return elements.get(id);}
  const sandbox={console,Math,performance:{now:()=>clock},document:{hidden:false,getElementById:el,addEventListener:(k,f)=>handlers[k]=f},window:{devicePixelRatio:1,addEventListener:(k,f)=>windowHandlers[k]=f},localStorage:{getItem(){throw Error('blocked');},setItem(){throw Error('blocked');}},ResizeObserver:class{observe(){}},requestAnimationFrame:fn=>frame=fn};
  vm.createContext(sandbox);vm.runInContext(scripts.join('\n').replace('game=new FlightMarket()','game=globalThis.testGame=new FlightMarket()'),sandbox);
  const press=(code,repeat=false,editing=false)=>handlers.keydown({code,repeat,target:{closest:()=>editing},preventDefault(){}});
  function advance(ms){for(let i=0;i<ms;i+=1000/60){clock+=1000/60;frame(clock);}}
  el('initial').value='2001';el('start').events.click();assert.equal(el('welcome').hidden,false);assert.ok(el('initial-error').textContent);
  el('initial').value='600';el('start').events.click();assert.equal(el('cash').textContent,'1,400.00');press('KeyA');assert.equal(el('cash').textContent,'1,260.00');assert.equal(el('paused').hidden,true);
  press('KeyA',true);assert.equal(el('cash').textContent,'1,260.00');press('KeyA',false,true);assert.equal(el('cash').textContent,'1,260.00');
  el('rate').value='20';el('rate').events.input();el('buy').events.click();assert.equal(el('cash').textContent,'1,008.00');assert.equal(el('paused').hidden,true);
  press('KeyD');assert.ok(Number(el('cash').textContent.replaceAll(',',''))>1008);advance(100);assert.notEqual(Number(el('price').textContent),128);
  el('rate').value='999';el('rate').events.input();el('rate').events.change();assert.equal(el('rate').value,'20');
  el('pause').events.click();const quote=el('price').textContent;advance(500);assert.equal(el('price').textContent,quote);assert.equal(el('paused').hidden,false);el('resume').events.click();advance(100);
  el('exit').events.click();assert.equal(el('ended').hidden,true);assert.equal(el('exit').disabled,true);for(let i=0;i<10000&&sandbox.testGame.score<8;i++){const next=sandbox.testGame.pipes.find(p=>!p.passed);if(Engine.pilot(sandbox.testGame.y,sandbox.testGame.vy,next.center))press('Space');advance(1000/60);}assert.equal(sandbox.testGame.score,8);press('KeyA',true);advance(100);assert.equal(el('exit').disabled,false);el('exit').events.click();assert.equal(el('ended').hidden,false);assert.equal(el('position').textContent,'0.00');assert.equal(el('final-equity').textContent,el('equity').textContent);
  const settled=el('cash').textContent;press('KeyA');press('KeyD');assert.equal(el('cash').textContent,settled);el('restart').events.click();assert.equal(el('welcome').hidden,false);assert.equal(el('cash').textContent,'2,000.00');
  el('start').events.click();advance(200);el('stage').events.pointerdown({target:{closest:()=>null},pointerType:'touch',preventDefault(){}});advance(100);
  sandbox.document.hidden=true;handlers.visibilitychange();assert.equal(el('paused').hidden,false);sandbox.document.hidden=false;handlers.visibilitychange();assert.equal(el('paused').hidden,false);el('resume').events.click();
  for(let i=0;i<35;i++){press('Space',true);advance(100);}assert.equal(el('ended').hidden,false);assert.equal(el('result-title').textContent,'本局失败');
});
test('Bird altitude drives price and OHLC; completed candles retain flight path',()=>{const a=new Engine(()=>.75),b=new Engine(()=>.75);a.start();b.start();b.y=270;const samples=[b.price];for(let i=0;i<20;i++){a.update(1/120);b.update(1/120);near(a.price,a.priceAt(a.y));near(b.price,b.priceAt(b.y));assert.ok(b.price>a.price);samples.push(b.price);}const k=b.history[0];near(k.open,128);near(k.high,Math.max(...samples));near(k.low,Math.min(...samples));near(k.close,b.price);assert.notEqual(JSON.stringify(a.history),JSON.stringify(b.history));const frozen=JSON.stringify(k);b.flap();b.update(.1);assert.equal(JSON.stringify(k),frozen);const price=b.price;b.cameraY+=100;b.sample();near(b.price,price);});
test('Fill ledger reconciles all cash movements and fees, and resets',()=>{const g=new Engine(()=>.75);g.start(600);g.trade('buy',20);g.y=250;g.sample();g.trade('sell',20);g.score=8;g.exit();const p=g.portfolio;assert.equal(g.executions.length,4);assert.equal(g.executions.reduce((s,f)=>s+f.cashDeltaCents,200000),p.cash);assert.equal(g.executions.reduce((s,f)=>s+f.feeCents,0),p.fees);assert.equal(p.realized,p.cash-p.initial);for(const f of g.executions){assert.ok(f.units>0);assert.equal(f.grossCents,f.side==='buy'?-f.cashDeltaCents-f.feeCents:f.cashDeltaCents+f.feeCents);}const n=g.executions.length;g.exit();assert.equal(g.executions.length,n);g.reset();assert.equal(g.executions.length,0);assert.equal(g.lastFill,null);});
console.log(`\n${passed} checks passed. Visual browser review is separate.`);
